name: Android CI
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: build
        
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk
          
